---
title: "nets"
output: html_document
date: "2025-08-09"
---

```{r setup}
library(igraph)

library(tidyverse)
library(influenceR)
library(keyplayer)


```

## Clusters


```{r , fig.width= 13 , fig.height = 12}
#creating an edgelist from data
edgelist <- read_csv("karate_el.csv", col_names = c("from", "to"))
head(edgelist)

#creating an igraph object
igraphobject <- graph_from_data_frame(edgelist, directed = FALSE)

#Choosing layout format: There are many!
layouts <- layout_with_kk(igraphobject)

### Other graph layouts: add_layout_(), component_wise(), layout_as_bipartite(), layout_as_star(), layout_as_tree(), layout_in_circle(), layout_nicely(), layout_on_grid(), layout_on_sphere(), layout_randomly(), layout_with_dh(), layout_with_fr(), layout_with_gem(), layout_with_graphopt(), layout_with_kk(), layout_with_lgl(), layout_with_mds(), layout_with_sugiyama(), merge_coords(), norm_coords(), normalize()

# plotting of initial graph
igraphobject <- set_edge_attr(igraphobject, "color", value = "black")

set.seed(1234)

plot(igraphobject, vertex.size = 16, vertex.color = "lightblue", vertex.label.color = "black", vertex.label.cex = 0.8, layout = layouts)

# Attaining membership of individuals in the network with a cluster walktrap algorithm, and saving it 
clustered <- cluster_walktrap(igraphobject)

# Saving cluster membership into a dataframe

membership_vec <- data.frame(node = V(igraphobject)$name, community = clustered$membership)

# We can see how many individuals are in each community
table(membership_vec$community)

#Add membership into the igraph object for plotting
V(igraphobject)$community <- clustered$membership

### I will showcase two options here. You can manually attach a certain colour scheme to the communities

memcolors <- adjustcolor(c("cyan", "gold", "deeppink", "royalblue", "green"), alpha=.6)


set.seed(1234) # to ensure reproducibility
plot(
   igraphobject,vertex.size = 16,
  vertex.color =  memcolors[V(igraphobject)$community],
  vertex.size = 15,
  vertex.label.cex = 0.8,
   vertex.label.color = "black",layout = layouts,
  main = "Karate Club Walktrap Communities"
)

### Or use in built functionality from igraph to plot the communities

set.seed(1234) # to ensure reproducibility
plot( clustered, #Add cluster object in front
   igraphobject,vertex.size = 16,
  vertex.color =  V(igraphobject)$community,
  vertex.size = 15,
  vertex.label.cex = 0.8,
   vertex.label.color = "black",layout = layouts,
  main = "Karate Club Walktrap Communities"
)

### Note: Edges to the next community are labelled in red, while those within a community are labelled black!

# Check modularity score
modularity(igraphobject, membership(clustered))

```

## Including Plots


```{r , fig.width= 13 , fig.height = 12}
### Let us first check the individuals that would be identified as important to remove in order to fracture the network by standard centrality metrics

# Top 5 nodes on betweenness centrality are John A, Mr Hi, Actor 33, Actor 3, Actor 32
between <- betweenness(igraphobject) 
between %>% sort(decreasing = T)
#V(igraphobject)$high_betweenness <- between >= 153

# Top 5 nodes on  degree centrality are John A, Mr Hi, Actor 33, Actor 3, Actor 2
degrees  <- degree(igraphobject) 
degrees  %>% sort(decreasing = T)


# Simulate deletion of highest centrality nodes in a new igraph object
node_deletion_of_highdegree <- delete_vertices(igraphobject, V(igraphobject)$name %in% c("Mr Hi", "John A", "Actor 33", "Actor 3", "Actor 2"))

set.seed(1234)

plot(node_deletion_of_highdegree, vertex.size = 16, vertex.color = "lightblue", vertex.label.color = "black", vertex.label.cex = 0.8, layout = layouts)


# Determine remaining communities to calculate modularity
clustered <- cluster_walktrap(node_deletion_of_highdegree)

# Check modularity score

modularity(node_deletion_of_highdegree, membership(clustered))

# Plot remaining communities (If you wish, may not be the most relevant question after deletions)

# Saving cluster membership into a dataframe

membership_vec <- data.frame(node = V(node_deletion_of_highdegree)$name, community = clustered$membership)

V(node_deletion_of_highdegree)$community <- clustered$membership

#If you still wish to highlight communities after deletion, ensure you are plotting communities with > 1 size since nodes might be isolated

commsize <- table(V(node_deletion_of_highdegree)$community)

actualcommunities <- names(commsize)[commsize > 1]


### Manually attach a certain colour scheme to the communities if you wish 

memcolors <- adjustcolor(c("cyan", "gold", "deeppink", "royalblue", "green"), alpha=.6)


set.seed(1234) # to ensure reproducibility
plot(
   node_deletion_of_highdegree,vertex.size = 16,
  vertex.color =  ifelse(V(node_deletion_of_highdegree)$community %in% actualcommunities, memcolors[V(node_deletion_of_highdegree)$community], "white"),
  vertex.size = 15,
  vertex.label.cex = 0.8,
   vertex.label.color = "black",layout = layouts,
  main = "Karate Club Walktrap Communities"
)



# Check modularity score

modularity(node_deletion_of_highdegree, membership(clustered))

```
### Using our keyplayers instead!
```{r , fig.width= 13 , fig.height = 12}

set.seed(1234)

results <- keyplayer::kpset(as_adjacency_matrix(igraphobject), size = 5 #Decide how many keyplayers you want
                            , type = "diffusion"
                            , method = "union"
                            , T = 1, binary = T)

results
V(igraphobject)$name[results$keyplayers]

# Simulate deletion of key players and re-plot
node_deletion_of_keyplayers <- delete_vertices(igraphobject, V(igraphobject)$name %in% V(igraphobject)$name[results$keyplayers])


set.seed(1234)

plot(node_deletion_of_keyplayers, vertex.size = 16, vertex.color = "lightblue", vertex.label.color = "black", vertex.label.cex = 0.8, layout = layouts)

# Determine remaining communities to calculate modularity
clustered <- cluster_walktrap(node_deletion_of_keyplayers)

# Check modularity score

modularity(node_deletion_of_keyplayers, membership(clustered))

# Plot remaining communities (If you wish, may not be the most relevant question after deletions)

# Saving cluster membership into a dataframe

membership_vec <- data.frame(node = V(node_deletion_of_keyplayers)$name, community = clustered$membership)

V(node_deletion_of_keyplayers)$community <- clustered$membership

#If you still wish to highlight communities after deletion, ensure you are plotting communities with > 1 size since nodes might be isolated

commsize <- table(V(node_deletion_of_keyplayers)$community)

actualcommunities <- names(commsize)[commsize > 1]


### Manually attach a certain colour scheme to the communities if you wish 

memcolors <- adjustcolor(c("cyan", "gold", "deeppink", "royalblue", "green"), alpha=.6)


set.seed(1234) # to ensure reproducibility
plot(
   node_deletion_of_keyplayers,vertex.size = 16,
  vertex.color =  ifelse(V(node_deletion_of_keyplayers)$community %in% actualcommunities, memcolors[V(node_deletion_of_keyplayers)$community], "white"),
  vertex.size = 15,
  vertex.label.cex = 0.8,
   vertex.label.color = "black",layout = layouts,
  main = "Karate Club Walktrap Communities"
)






```

### keyplayers surpasses centrality at nodes
```{r , fig.width= 9 , fig.height = 10}
# Simulate deletion of highest centrality nodes and re-plot
node_deletion_of_highdegree <- delete_vertices(igraphobject, V(igraphobject)$name %in% c("Mr Hi", "John A", "Actor 33", "Actor 3", "Actor 2","Actor 4", "Actor 32", "Actor 9" ))


plot(
  node_deletion_of_highdegree,
  vertex.color = membership(cluster_walktrap(node_deletion_of_highdegree)),
  vertex.size = 16, vertex.color = "lightblue", vertex.label.color = "black", vertex.label.cex = 0.8, layout = layouts
)


clustered <- cluster_walktrap(node_deletion_of_highdegree)

modularity(node_deletion_of_highdegree, membership(clustered))


set.seed(1234)

results <- keyplayer::kpset(as_adjacency_matrix(igraphobject), size = 8, type = "diffusion", method = "union", T = 1, binary = T)

results
V(igraphobject)$name[results$keyplayers]

# Simulate deletion of key players and re-plot
node_deletion_of_keyplayers <- delete_vertices(igraphobject, V(igraphobject)$name %in% V(igraphobject)$name[results$keyplayers])


plot(
  node_deletion_of_keyplayers,
  vertex.color = membership(cluster_walktrap(node_deletion_of_keyplayers)),
  vertex.size = 16, vertex.color = "lightblue", vertex.label.color = "black", vertex.label.cex = 0.8, layout = layouts
)


clustered <- cluster_walktrap(node_deletion_of_keyplayers)

modularity(node_deletion_of_keyplayers, membership(clustered))
```
